// <auto-generated />
using System;
using InnoTechApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InnoTechApp.Data.Migrations
{
    [DbContext(typeof(InnoTechAppDbContext))]
    partial class InnoTechAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("InnoTechApp.Core.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Description = "Lorem pla pla pla pla pla",
                            Name = "Asp.Net Core",
                            Price = 112f
                        },
                        new
                        {
                            CourseId = 2,
                            Description = "Lorem pla pla pla pla pla",
                            Name = "Blazor",
                            Price = 500f
                        },
                        new
                        {
                            CourseId = 3,
                            Description = "Lorem pla pla pla pla pla",
                            Name = "Entity Framework Core Getting Started",
                            Price = 300f
                        });
                });

            modelBuilder.Entity("InnoTechApp.Core.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            CourseId = 1,
                            Date = new DateTime(2021, 1, 23, 1, 22, 7, 173, DateTimeKind.Local).AddTicks(6934),
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            CourseId = 2,
                            Date = new DateTime(2021, 3, 24, 1, 22, 7, 175, DateTimeKind.Local).AddTicks(8601),
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 3,
                            CourseId = 3,
                            Date = new DateTime(2021, 2, 22, 1, 22, 7, 175, DateTimeKind.Local).AddTicks(8762),
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 4,
                            CourseId = 1,
                            Date = new DateTime(2021, 1, 23, 21, 22, 7, 175, DateTimeKind.Local).AddTicks(8771),
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 5,
                            CourseId = 1,
                            Date = new DateTime(2021, 1, 23, 1, 42, 7, 175, DateTimeKind.Local).AddTicks(8795),
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 6,
                            CourseId = 3,
                            Date = new DateTime(2021, 1, 23, 21, 22, 7, 175, DateTimeKind.Local).AddTicks(8813),
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 7,
                            CourseId = 2,
                            Date = new DateTime(2021, 2, 23, 1, 22, 7, 175, DateTimeKind.Local).AddTicks(8816),
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 8,
                            CourseId = 2,
                            Date = new DateTime(2021, 1, 23, 7, 22, 7, 175, DateTimeKind.Local).AddTicks(8891),
                            StudentId = 4
                        });
                });

            modelBuilder.Entity("InnoTechApp.Core.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Age = 21,
                            Name = "Mohammad Fayed"
                        },
                        new
                        {
                            StudentId = 2,
                            Age = 9,
                            Name = "Ahmed Fayed"
                        },
                        new
                        {
                            StudentId = 3,
                            Age = 21,
                            Name = "Amr Alaa"
                        },
                        new
                        {
                            StudentId = 4,
                            Age = 21,
                            Name = "Omar Morgan"
                        });
                });

            modelBuilder.Entity("InnoTechApp.Core.Enrollment", b =>
                {
                    b.HasOne("InnoTechApp.Core.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnoTechApp.Core.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InnoTechApp.Core.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("InnoTechApp.Core.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
